MTDSA-16862: added dynamic GTS to v1 documentation
hmrc/obligations-api pull request #114
Opened 2023-05-19 12:58 UTC by LouiseWong98

2023-05-19 14:36 UTC, rhysconnor submitted a review, later dismissed
LGTM - will wait to merge!

2023-05-26 10:41 UTC, ben-HMRC commented on resources/public/api/conf/1.0/retrieve_income_tax_eops.yaml
> +            <p>Following response values will change to correspond to the values submitted in the request:
"Following" to "The following"

2023-05-26 10:41 UTC, ben-HMRC commented on resources/public/api/conf/1.0/retrieve_income_tax_income_expenditure.yaml
> +            <p>Following response values will change to correspond to the values submitted in the request:
"Following" to "The following"

2023-05-26 10:48 UTC, ben-HMRC requested changes
See comments on individual lines

2023-06-01 12:55 UTC, rhysconnor approved these changes
LGTM

2023-06-01 12:55 UTC, merged